apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 5000 # Container port inside the pod
      nodePort: 30007  # Node port (must be between 30000-32767)
